name: Release

on:
  push:
    branches: [ master ]
    tags: ["*"]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache Ivy
      uses: actions/cache@v1
      with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-ivy-${{ hashFiles('scalafix/*.sbt') }}-${{ hashFiles('scalafix/project/*.*') }}
        restore-keys: ${{ runner.os }}-ivy-
    - name: Cache Sbt
      uses: actions/cache@v1
      with:
        path: ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('scalafix/*.sbt') }}-${{ hashFiles('scalafix/project/*.*') }}
        restore-keys: ${{ runner.os }}-sbt-
    - name: Cache Coursier
      uses: actions/cache@v1
      with:
        path: ~/.cache/coursier
        key: ${{ runner.os }}-coursier-${{ hashFiles('scalafix/*.sbt') }}-${{ hashFiles('scalafix/project/*.*') }}
        restore-keys: ${{ runner.os }}-coursier-
    - uses: olafurpg/setup-scala@v7
    - uses: olafurpg/setup-gpg@v2
    - run: git fetch --unshallow
    - name: Publish ${{ github.ref }}
      run: cd scalafix && sbt ci-release
      env:
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        PGP_SECRET: ${{ secrets.PGP_SECRET }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
