name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test on ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [graalvm@20, adopt@1.8]

    steps:
    - uses: actions/checkout@v2
    - name: Cache Ivy
      uses: actions/cache@v1
      with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-ivy-${{ hashFiles('scalafix/*.sbt') }}-${{ hashFiles('scalafix/project/*.*') }}
        restore-keys: ${{ runner.os }}-ivy-
    - name: Cache Sbt
      uses: actions/cache@v1
      with:
        path: ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('scalafix/*.sbt') }}-${{ hashFiles('scalafix/project/*.*') }}
        restore-keys: ${{ runner.os }}-sbt-
    - name: Cache Coursier
      uses: actions/cache@v1
      with:
        path: ~/.cache/coursier
        key: ${{ runner.os }}-coursier-${{ hashFiles('scalafix/*.sbt') }}-${{ hashFiles('scalafix/project/*.*') }}
        restore-keys: ${{ runner.os }}-coursier-
    - name: Set up scala
      uses: olafurpg/setup-scala@v7
      with:
        java-version: ${{ matrix.java }}
    - name: Run tests
      run: cd scalafix && sbt ++test
